# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

puts "Destroying Diners 🍽" 
Diner.destroy_all
puts "Destroying Chef 👩🏼‍🍳"
Chef.destroy_all

# Diners
buffy = Diner.create(name: "Buffy Summers", password: "GirlPower", email: "buffy@theslayer.com", location: "Sunnydale, CA", profile_photo: "https://upload.wikimedia.org/wikipedia/en/a/a2/S514_Buffy.png" )
willow = Diner.create(name: "Willow Rosenberg", password: "GoodWitch", email: "willow@theslayer.com", location: "Sunnydale, CA", profile_photo: "https://pbs.twimg.com/profile_images/1247562103080259585/JOJ277bB.jpg")
giles = Diner.create(name: "Rupert Giles", password: "IloveLibraries", email: "giles@watchers.com", location: "Sunnydale, CA",  profile_photo: "https://vignette.wikia.nocookie.net/buffymegaxover/images/a/a3/Rupert_Giles.jpg/revision/latest/scale-to-width-down/340?cb=20150922044215" )
xander = Diner.create(name: "Xander Harris", password: "Anya4Ever", email: "xander@theslayer.com", location: "Sunnydale, CA", profile_photo: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcS2ybZK9ObrX0yF94GACrfzX-Y6zN_JzchWhg&usqp=CAU")
spike = Diner.create(name: "William 'The Bloody' 'Spike' Pratt", password: "Deathisyourart", email: "williamthebloody@vamp.com", location: "Sunnydale, CA", profile_photo: "https://www.factinate.com/wp-content/uploads/2018/04/Spike-from-Buffy-the-Vampire-Slayer.jpg")

cordelia = Chef.create(name: "Cordelia Chase", password: "IloveShopping", email: "cordelia@angeldet.com", bio: "I was a cheerleader, a princess, and a warrior. I've turned to cooking as a comfort from my visions, and to keep me distracted from being hunted by an evil law firm. Can't wait to share my table with you!", neighborhood: "The Bronze", cuisine: "Italian", address: "123 Sunnydale Ave. Sunnydale, CA", hours: "Daily 5-9", profile_photo: "https://upload.wikimedia.org/wikipedia/en/thumb/d/da/CordeliaChase.jpg/220px-CordeliaChase.jpg", home_photo: "https://media.architecturaldigest.com/photos/57ffe6f106d6622c7c27fd7d/master/w_1600%2Cc_limit/midcentury-modern-dining-rooms-08.jpg" )
angel = Chef.create(name: "Liam 'Angelus' 'Angel'", password: "SoulVamp", email: "angel@angeldet.com", bio: "Vampire with a soul. Former CEO of Angel Investigations, former CEO of Wolfram & Hart. Feeding others feeds my soul.", neighborhood: "Hellmouth", cuisine: "Traditional English/Irish", address: "321 Sunnydale Ave. Sunnydale, CA", hours: "Daily 5-9", profile_photo: "https://us.v-cdn.net/6030815/uploads/294/M99P19MI8BOU.jpg", home_photo: "https://media.architecturaldigest.com/photos/57ffe6ef04c799614d985dd1/master/w_1600%2Cc_limit/midcentury-modern-dining-rooms-04.jpg")
tara = Chef.create(name: "Tara Maclay", password: "ImUnderYourSpell", email: "tara@ucsunnydale.edu", bio: "Food heals the soul. My dishes are based in ayurveda, using plants and herbs to heal and strengthen the body. I cook instinctually, following the guidance of the Earth Mother. Welcome to my witchy kitchen.", neighborhood: "The Magic Box", cuisine: "Vegetarian", address: "456 Hellmouth Lane, Sunnydale, CA", hours: "Daily 5-9, and until midnight on the full moon", profile_photo: "https://tvline.com/wp-content/uploads/2017/03/amber-benson-tara-buffy.png?w=619", home_photo: "https://media.architecturaldigest.com/photos/57ffe6f204c799614d985dd5/master/w_1600%2Cc_limit/midcentury-modern-dining-rooms-09.jpg")
anya = Chef.create(name: "Anya 'Anyanka' Jenkins", password: "Ihatebunnies", email: "anya@vengeance.org", bio: "Former Patron Saint of the Women Scorned turned home cook! Don't worry, I'm out of the vengeance business and now I just love to nourish folks with my flavorful dishes from the old country.", neighborhood: "Hellmouth", cuisine: "Eastern European", address: "666 Vengeance St. Sunnydale, CA", hours: "Daily 5-9", profile_photo: "https://i.ytimg.com/vi/rFhJW8EDynA/hqdefault.jpg", home_photo: "https://media.architecturaldigest.com/photos/57ffe6f206d6622c7c27fd7e/master/w_1600%2Cc_limit/midcentury-modern-dining-rooms-10.jpg" )
oz = Chef.create(name: "Daniel 'Oz' Osbourne", password: "howlatthemoon", email: "oz@dingoesate.co", bio: "Former touring musician. Met the love of my life, Bayarmaa in Tibet. Proud husband and stay-at-home dad. Cooking became my passion while raising my son.Come on over, I'd love to have you for dinner.", neighborhood: "The Bronze", cuisine: "Pan-Asian", address: "131 Werewolf Way, Sunnydale, CA", hours: "Daily 5-9, closed during the full moon", profile_photo: "https://static.comicvine.com/uploads/original/3/35500/1238309-12.jpg", home_photo: "https://media.architecturaldigest.com/photos/57ffe6ee06d6622c7c27fd7b/master/w_1600%2Cc_limit/midcentury-modern-dining-rooms-01.qch.jpg")